### ISSUE TITLE
Pusher Credentials in Comments.vue

### ISSUE THREAD

**Issue by cmlejeune** [Ethiel97/comments-laravel-pusher#1]
APP_ID or APP_KEY in resources/js/components/Comments.vue 
// APP_KEY worked for me; APP_ID did not work

From the demo at Pusher:  https://pusher.com/tutorials/live-comments-laravel-vue
let pusher = new Pusher(`YOUR_PUSHER_APP_ID`
I think the above should be:  new Pusher(`YOUR_PUSHER_APP_KEY'
// again, that worked for me
Thanks for the excellent work and tutorial!

**Comment by Ethiel97** [comment]
Ooh ok thanks for the remark. I'll make the edits. If you feel satisfied with the work you can follow me on [Twitter😉](https://twitter.com/ethiel97). More great content are coming
